import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import {
  deleteDoc, doc, getDoc, serverTimestamp, setDoc, writeBatch,
  type Firestore,
  type Timestamp,
} from 'firebase/firestore'
import type { RulesTestEnvironment } from '@firebase/rules-unit-testing'
import { buildInventoryItemDocument, buildInventoryItemUpdate } from '@/domain/inventory-payloads'
import { buildInventoryUnitDocument } from '@/domain/inventory-unit-payloads'
import { EMPTY_CONDITION_COUNTS } from '@/domain/inventory'
import { mirrorsOf, serializedMirrorInput, withUnitRemoved } from '@/domain/inventory-unit'
import {
  ADMIN, CODE_A, CODE_B, EDIT_INVENTORY, ORG_A, ORG_B, OUTSIDER, TEAM_COSTUME, TEAM_LIGHTING,
  TEAM_OTHER_ORG, VIEW_INVENTORY, assertFails, assertSucceeds, createTestEnvironment,
  seedMembership, seedOrganization, seedTeam,
} from './helpers'
import type { InventoryItem, InventoryUnit } from '@/types/inventory'

/**
 * QA-11: deleting a unit that should never have existed.
 *
 * Equipment leaves the inventory by being retired, and retiring keeps its
 * history — that is why this collection refused every delete until now. The one
 * exception is a unit generated by mistake that nothing has happened to yet,
 * and the whole safety of the exception rests on Rules being able to tell those
 * two apart *without a query*, because Rules cannot query.
 *
 * They can, because of an invariant enforced on every earlier write: a status
 * change must set `last_lifecycle_event_id` in the same commit, and a trip to
 * maintenance must append to `maintenance_record_ids`. A unit carrying neither
 * has never moved, so nothing in `asset_events` or `maintenance_records` can
 * name it. These tests are what says that reasoning is actually enforced.
 */

let environment: RulesTestEnvironment

const EDITOR = 'uid-hd-editor'
const VIEWER = 'uid-hd-viewer'
const COSTUME_EDITOR = 'uid-hd-costume'

const ITEM = 'itemHARDDELETEAAAAAA'
const ITEM_OTHER_ORG = 'itemHDOTHERORGAAAAAA'

const CLEAN_UNIT = 'unitHDCLEANAAAAAAAAA'
const OTHER_ORG_UNIT = 'unitHDOTHERORGAAAAAA'

beforeAll(async () => { environment = await createTestEnvironment() })
afterAll(async () => environment.cleanup())

function db(uid: string | null): Firestore {
  const context = uid ? environment.authenticatedContext(uid) : environment.unauthenticatedContext()
  return context.firestore() as unknown as Firestore
}

/** A serialized parent holding exactly the units the test seeds under it. */
function itemPayload(o: { itemId?: string; organizationId?: string; teamId?: string; uid?: string
  units?: { status: 'available'; condition: 'good' }[] } = {}) {
  const units = o.units ?? [{ status: 'available' as const, condition: 'good' as const }]
  const base = buildInventoryItemDocument({
    itemId: o.itemId ?? ITEM,
    organizationId: o.organizationId ?? ORG_A,
    uid: o.uid ?? ADMIN,
    now: serverTimestamp,
    input: {
      name: 'Wireless Handheld',
      category: 'Microphones',
      teamId: o.teamId ?? TEAM_LIGHTING,
      trackingMode: 'serialized',
      quantityTotal: units.length,
      quantityAvailable: units.length,
      conditionCounts: { ...EMPTY_CONDITION_COUNTS, good: units.length },
      location: 'Sound Booth',
    },
  })

  return {
    ...base,
    unit_counts: {
      active_total: units.length,
      available: units.length,
      unusable_on_hand: 0,
      in_use: 0,
      in_maintenance: 0,
      lost: 0,
      retired: 0,
    },
  }
}

function unitPayload(o: {
  unitId?: string; organizationId?: string; inventoryItemId?: string; teamId?: string
  status?: 'available' | 'in_use' | 'lost' | 'retired'
  extra?: Record<string, unknown>
} = {}) {
  const status = o.status ?? 'available'
  return {
    ...buildInventoryUnitDocument({
      unitId: o.unitId ?? CLEAN_UNIT,
      organizationId: o.organizationId ?? ORG_A,
      inventoryItemId: o.inventoryItemId ?? ITEM,
      uid: ADMIN,
      now: serverTimestamp,
      input: {
        owningTeamId: o.teamId ?? TEAM_LIGHTING,
        assetCode: 'MIC-001',
        condition: 'good',
        status,
        storageLocation: 'Sound Booth',
        retirementReason: status === 'retired' ? 'disposed' : null,
        usingTeamId: status === 'in_use' ? (o.teamId ?? TEAM_LIGHTING) : null,
        usingMemberUid: null,
      },
    }),
    ...(o.extra ?? {}),
  }
}

/** Seed a unit directly, bypassing Rules, so its shape is exactly as stated. */
async function seedUnit(unitId: string, payload: Record<string, unknown>) {
  await environment.withSecurityRulesDisabled(async (context) => {
    const store = context.firestore() as unknown as Firestore
    await setDoc(doc(store, 'inventory_units', unitId), payload)
  })
}

/**
 * The write the service sends: the unit removed and the parent's mirrors moved
 * down, in one batch. Rules require both halves.
 */
async function deleteWithParent(uid: string, unitId: string, itemId = ITEM) {
  let item = {} as InventoryItem
  let unit = {} as InventoryUnit

  await environment.withSecurityRulesDisabled(async (context) => {
    const store = context.firestore() as unknown as Firestore
    item = (await getDoc(doc(store, 'inventory_items', itemId))).data() as InventoryItem
    unit = (await getDoc(doc(store, 'inventory_units', unitId))).data() as InventoryUnit
  })

  const next = withUnitRemoved(mirrorsOf(item), unit)
  const store = db(uid)
  const batch = writeBatch(store)

  batch.delete(doc(store, 'inventory_units', unitId))
  batch.set(doc(store, 'inventory_items', itemId), buildInventoryItemUpdate({
    itemId,
    organizationId: item.organization_id,
    createdByUid: item.created_by_uid,
    createdAt: item.created_at as unknown as Timestamp,
    now: serverTimestamp,
    input: serializedMirrorInput(item, next),
  }))

  return batch.commit()
}

beforeEach(async () => {
  await environment.clearFirestore()

  await seedOrganization(environment, { organizationId: ORG_A, adminUid: ADMIN, code: CODE_A })
  await seedOrganization(environment, { organizationId: ORG_B, adminUid: OUTSIDER, code: CODE_B })

  await seedTeam(environment, { teamId: TEAM_LIGHTING, organizationId: ORG_A, name: 'Lighting' })
  await seedTeam(environment, { teamId: TEAM_COSTUME, organizationId: ORG_A, name: 'Costume' })
  await seedTeam(environment, { teamId: TEAM_OTHER_ORG, organizationId: ORG_B, name: 'Sound' })

  await seedMembership(environment, {
    organizationId: ORG_A, uid: EDITOR, teamIds: [TEAM_LIGHTING], permissions: EDIT_INVENTORY,
  })
  await seedMembership(environment, {
    organizationId: ORG_A, uid: VIEWER, teamIds: [TEAM_LIGHTING], permissions: VIEW_INVENTORY,
  })
  await seedMembership(environment, {
    organizationId: ORG_A, uid: COSTUME_EDITOR, teamIds: [TEAM_COSTUME], permissions: EDIT_INVENTORY,
  })

  await environment.withSecurityRulesDisabled(async (context) => {
    const store = context.firestore() as unknown as Firestore
    await setDoc(doc(store, 'inventory_items', ITEM), itemPayload())
    await setDoc(doc(store, 'inventory_items', ITEM_OTHER_ORG), itemPayload({
      itemId: ITEM_OTHER_ORG, organizationId: ORG_B, teamId: TEAM_OTHER_ORG, uid: OUTSIDER,
    }))
    await setDoc(doc(store, 'inventory_units', CLEAN_UNIT), unitPayload())
    await setDoc(doc(store, 'inventory_units', OTHER_ORG_UNIT), unitPayload({
      unitId: OTHER_ORG_UNIT, organizationId: ORG_B, inventoryItemId: ITEM_OTHER_ORG,
      teamId: TEAM_OTHER_ORG,
    }))
  })
})

describe('a unit nothing has happened to can be deleted', () => {
  it('lets an inventory editor on the owning team delete it', async () => {
    await assertSucceeds(deleteWithParent(EDITOR, CLEAN_UNIT))
  })

  it('lets the Admin delete it', async () => {
    await assertSucceeds(deleteWithParent(ADMIN, CLEAN_UNIT))
  })

  it('leaves the parent counting one fewer unit', async () => {
    await assertSucceeds(deleteWithParent(EDITOR, CLEAN_UNIT))

    await environment.withSecurityRulesDisabled(async (context) => {
      const store = context.firestore() as unknown as Firestore
      const item = (await getDoc(doc(store, 'inventory_items', ITEM))).data() as InventoryItem
      const gone = await getDoc(doc(store, 'inventory_units', CLEAN_UNIT))

      expect(gone.exists()).toBe(false)
      expect(item.unit_counts?.active_total).toBe(0)
      expect(item.unit_counts?.available).toBe(0)
      expect(item.quantity_total).toBe(0)
      expect(item.quantity_available).toBe(0)
      expect(item.condition_counts.good).toBe(0)
    })
  })
})

describe('a unit with anything attached to it cannot be deleted', () => {
  // Each of these is a pointer the unit carries, and each is the trace of a
  // record elsewhere that would be orphaned by deleting it.
  const LINKED: [string, Record<string, unknown>][] = [
    ['a lifecycle event, so an asset event names it', { last_lifecycle_event_id: 'evt-1' }],
    ['a repair history', { maintenance_record_ids: ['mnt-1'] }],
    ['a repair it is away for', { current_maintenance_record_id: 'mnt-1' }],
    ['a repair planned for it', { planned_maintenance_record_id: 'mnt-1' }],
  ]

  it.each(LINKED)('refuses one with %s', async (_label, extra) => {
    await seedUnit(CLEAN_UNIT, unitPayload({ extra }))
    await assertFails(deleteWithParent(EDITOR, CLEAN_UNIT))
  })

  it.each(['in_use', 'lost', 'retired'] as const)('refuses one that is %s', async (status) => {
    // Reaching any of these required a lifecycle event, so the unit is not new
    // and its history is exactly what deleting would destroy.
    await seedUnit(CLEAN_UNIT, unitPayload({ status }))
    await assertFails(deleteWithParent(EDITOR, CLEAN_UNIT))
  })

  it('refuses one somebody is holding', async () => {
    await seedUnit(CLEAN_UNIT, unitPayload({ extra: { using_team_id: TEAM_LIGHTING } }))
    await assertFails(deleteWithParent(EDITOR, CLEAN_UNIT))
  })
})

describe('deleting is bounded by the same permission as editing', () => {
  it('refuses a member who may only view the inventory', async () => {
    await assertFails(deleteWithParent(VIEWER, CLEAN_UNIT))
  })

  it('refuses an editor on a different team', async () => {
    // Team scope is what authorizes writing a unit, and deleting is a write.
    await assertFails(deleteWithParent(COSTUME_EDITOR, CLEAN_UNIT))
  })

  it('refuses a signed-out visitor', async () => {
    await assertFails(deleteDoc(doc(db(null), 'inventory_units', CLEAN_UNIT)))
  })

  it('refuses somebody from another organization', async () => {
    await assertFails(deleteWithParent(EDITOR, OTHER_ORG_UNIT, ITEM_OTHER_ORG))
    await assertFails(deleteWithParent(OUTSIDER, CLEAN_UNIT))
  })
})

describe('the parent cannot be left claiming a unit that is gone', () => {
  it('refuses a delete that does not touch the parent at all', async () => {
    // The whole failure this guards: the unit disappears and the item goes on
    // reporting a piece of equipment nobody can find.
    await assertFails(deleteDoc(doc(db(EDITOR), 'inventory_units', CLEAN_UNIT)))
  })

  it('refuses a delete whose parent update does not drop a unit', async () => {
    let item = {} as InventoryItem
    await environment.withSecurityRulesDisabled(async (context) => {
      const store = context.firestore() as unknown as Firestore
      item = (await getDoc(doc(store, 'inventory_items', ITEM))).data() as InventoryItem
    })

    const store = db(EDITOR)
    const batch = writeBatch(store)
    batch.delete(doc(store, 'inventory_units', CLEAN_UNIT))
    // The parent is written, but its counts are left exactly as they were.
    batch.set(doc(store, 'inventory_items', ITEM), buildInventoryItemUpdate({
      itemId: ITEM,
      organizationId: item.organization_id,
      createdByUid: item.created_by_uid,
      createdAt: item.created_at as unknown as Timestamp,
      now: serverTimestamp,
      input: serializedMirrorInput(item, mirrorsOf(item)),
    }))

    await assertFails(batch.commit())
  })
})

describe('nothing else became deletable', () => {
  it('still refuses deleting the inventory item itself', async () => {
    await assertFails(deleteDoc(doc(db(ADMIN), 'inventory_items', ITEM)))
  })
})
